FROM node:22

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# install dependencies
COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

# copy project
COPY . .

WORKDIR /usr/src/app/src/app/backend
EXPOSE 5000
CMD ["node", "server.js"]
