FROM node:22

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# کپی package.json اصلی و نصب dependencies
COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm approve-builds || true

# کپی کل پروژه
COPY . .

WORKDIR /usr/src/app/src/app
EXPOSE 3000
CMD ["pnpm", "dev"]
